# Generated by Django 2.2.4 on 2019-08-13 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ap_id', models.IntegerField(unique=True)),
                ('client_count', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('ap_group', models.CharField(max_length=100)),
                ('is_up', models.BooleanField(default=False)),
                ('mac_address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.IntegerField(unique=True)),
                ('username', models.CharField(max_length=100)),
                ('mac_address', models.CharField(max_length=50)),
                ('device_type', models.CharField(max_length=100)),
                ('vendor', models.CharField(max_length=100)),
                ('signal', models.IntegerField()),
                ('role', models.CharField(max_length=100)),
                ('auth_status', models.BooleanField(default=False)),
                ('assoc_status', models.BooleanField(default=False)),
                ('rssi', models.IntegerField()),
                ('snr', models.IntegerField()),
                ('ap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treatingxml.AP')),
            ],
        ),
    ]
